# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "version update"
    registries:
      - google
      - maven-central
    groups:
      kotlin-ksp-compose:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "androidx.compose.compiler:compiler"
    open-pull-requests-limit: 10
          
registries:
  google:
    type: maven-repository
    url: "https://maven.google.com/"
  maven-central:
    type: maven-repository
    url: "https://repo.maven.apache.org/maven2"
