name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3.3.2

      - name: Get local.properties from secret
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > ./local.properties

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2

      - name: Assemble build types
        run: ./gradlew :app:assembleDebug

      - name: Run unit tests
        run: ./gradlew test

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: APKs
          path: '**/build/outputs/apk/**/*.apk'
          
      - name: Upload test results
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test-results
          path: '**/build/test-results/test*UnitTest/*.xml'
          
  androidTest:
    needs: build-and-test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [26, 30]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3.3.2

      - name: Get local.properties from secret
        run: echo "${{ secrets.LOCAL_PROPERTIES }}" > ./local.properties

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.2

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2.30.1
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedDebugAndroidTest --daemon

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4.3.3
        with:
          name: test-reports-${{ matrix.api-level }}
          path: '**/build/reports/androidTests'
