name: Dependabot auto-merge
on: pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2

      - name: Setup Java JDK 17
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.3.0

      - name: Check build-logic
        run: ./gradlew check -p build-logic

      - name: Run unit tests
        run: ./gradlew test

      - name: Assemble build types
        run: ./gradlew :app:assembleDebug :benchmark:assemble

      - name: Upload build outputs (APKs)
        uses: actions/upload-artifact@v4.3.1
        with:
          name: APKs
          path: '**/build/outputs/apk/**/*.apk'

      - name: Upload test results
        uses: actions/upload-artifact@v4.3.1
        with:
          name: test-results
          path: '**/build/test-results/test*UnitTest/*.xml'

  dependabot:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.0.0
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Enable auto-merge for Dependabot PRs
        if: |
          steps.metadata.outputs.update-type == 'version-update:semver-patch' || 
          steps.metadata.outputs.update-type == 'version-update:semver-minor'
        run: gh pr merge --auto --squash --delete-branch "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
